export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const UNAUTH_REQUEST = 'UNAUTH_REQUEST';
export const UNAUTH_SUCCESS = 'UNAUTH_SUCCESS';
export const UNAUTH_FAILURE = 'UNAUTH_FAILURE';

export const MARKETS_REQUEST = 'MARKETS_SUCCESS';
export const MARKETS_SUCCESS = 'MARKETS_SUCCESS';
export const MARKETS_FAILURE = 'MARKETS_FAILURE';

export const MARKET_REQUEST = 'MARKET_SUCCESS';
export const MARKET_SUCCESS = 'MARKET_SUCCESS';
export const MARKET_FAILURE = 'MARKET_FAILURE';

export const SELECT_EPIC = 'SELECT_EPIC';

export const MARKET_UPDATE = 'MARKET_UPDATE';
